import type { SiteContent } from './content'

/** Size of public/og.png, generated by `pnpm brand`. */
const OG_IMAGE = { path: '/og.png', width: 1200, height: 630 }

const escapeHtml = (value: string) =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')

/**
 * The page's <title> and metadata, built from content so nothing is written
 * twice. The description reuses the hero summary; the title pairs the full
 * name with the role. `siteUrl` is the absolute production origin (no
 * trailing slash), used for the canonical URL and the preview image.
 */
export function renderHead(content: SiteContent, siteUrl: string): string {
  const title = `${content.person.fullName} · ${content.hero.role}`
  const description = content.hero.summary
  const url = `${siteUrl}/`
  const image = `${siteUrl}${OG_IMAGE.path}`

  const tags: [string, Record<string, string>][] = [
    ['meta', { name: 'description', content: description }],
    ['link', { rel: 'canonical', href: url }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: content.person.fullName }],
    ['meta', { property: 'og:title', content: title }],
    ['meta', { property: 'og:description', content: description }],
    ['meta', { property: 'og:url', content: url }],
    ['meta', { property: 'og:image', content: image }],
    ['meta', { property: 'og:image:width', content: String(OG_IMAGE.width) }],
    ['meta', { property: 'og:image:height', content: String(OG_IMAGE.height) }],
    ['meta', { property: 'og:image:alt', content: content.meta.ogImageAlt }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['meta', { name: 'twitter:title', content: title }],
    ['meta', { name: 'twitter:description', content: description }],
    ['meta', { name: 'twitter:image', content: image }],
    ['meta', { name: 'twitter:image:alt', content: content.meta.ogImageAlt }],
  ]

  const rendered = tags.map(([tag, attrs]) => {
    const attributes = Object.entries(attrs)
      .map(([key, value]) => `${key}="${escapeHtml(value)}"`)
      .join(' ')
    return `<${tag} ${attributes} />`
  })

  return [`<title>${escapeHtml(title)}</title>`, ...rendered].join('\n    ')
}
